// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CabinetAdminCategoriesEditDialog: typeof import('./components/cabinet/admin/categories/edit-dialog.vue')['default']
    CabinetAdminCategoriesForm: typeof import('./components/cabinet/admin/categories/form.vue')['default']
    CabinetAdminCategoriesNewDialog: typeof import('./components/cabinet/admin/categories/new-dialog.vue')['default']
    CabinetAdminCategoriesTable: typeof import('./components/cabinet/admin/categories/table.vue')['default']
    CabinetAdminChecksTable: typeof import('./components/cabinet/admin/checks/table.vue')['default']
    CabinetAdminCustomersTable: typeof import('./components/cabinet/admin/customers/table.vue')['default']
    CabinetAdminEmployeesEditDialog: typeof import('./components/cabinet/admin/employees/edit-dialog.vue')['default']
    CabinetAdminEmployeesForm: typeof import('./components/cabinet/admin/employees/form.vue')['default']
    CabinetAdminEmployeesNewDialog: typeof import('./components/cabinet/admin/employees/new-dialog.vue')['default']
    CabinetAdminEmployeesTable: typeof import('./components/cabinet/admin/employees/table.vue')['default']
    CabinetAdminNavbar: typeof import('./components/cabinet/admin/navbar.vue')['default']
    CabinetAdminProductsEditDialog: typeof import('./components/cabinet/admin/products/edit-dialog.vue')['default']
    CabinetAdminProductsForm: typeof import('./components/cabinet/admin/products/form.vue')['default']
    CabinetAdminProductsNewDialog: typeof import('./components/cabinet/admin/products/new-dialog.vue')['default']
    CabinetAdminProductsTable: typeof import('./components/cabinet/admin/products/table.vue')['default']
    CabinetCashierCheckTable: typeof import('./components/cabinet-cashier-check-table.vue')['default']
    CabinetCashierCustomerCard: typeof import('./components/cabinet-cashier-customer-card.vue')['default']
    CabinetCashierCustomerForm: typeof import('./components/cabinet-cashier-customer-form.vue')['default']
    CabinetCashierCustomerScanDialog: typeof import('./components/cabinet-cashier-customer-scan-dialog.vue')['default']
    CabinetCashierCustomersTable: typeof import('./components/cabinet/cashier/customers/table.vue')['default']
    CabinetCashierNavbar: typeof import('./components/cabinet-cashier-navbar.vue')['default']
    CabinetCashierPicker: typeof import('./components/cabinet/cashier-picker.vue')['default']
    CabinetChecksTable: typeof import('./components/cabinet/checks/table.vue')['default']
    CabinetCheckTableItem: typeof import('./components/cabinet-check-table-item.vue')['default']
    CabinetCustomerPropInput: typeof import('./components/cabinet-customer-prop-input.vue')['default']
    CabinetCustomersTable: typeof import('./components/cabinet/customers/table.vue')['default']
    CabinetProductsCategorySelector: typeof import('./components/cabinet-products-category-selector.vue')['default']
    CabinetProductsTable: typeof import('./components/cabinet/products/table.vue')['default']
    DatePropInput: typeof import('./components/date-prop-input.vue')['default']
    DateRangePicker: typeof import('./components/date-range-picker.vue')['default']
    GenericForm: typeof import('./components/generic-form.vue')['default']
    NumberPropInput: typeof import('./components/number-prop-input.vue')['default']
    RoleDropdown: typeof import('./components/role-dropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableButtons: typeof import('./components/table-buttons.vue')['default']
    TextPropInput: typeof import('./components/text-prop-input.vue')['default']
    UpcInput: typeof import('./components/upc-input.vue')['default']
  }
}
